[project]
name = "MarketLab"
dynamic = ["version"]
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "yfinance>=0.2.66",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]

[tool.ruff.lint]
select = ["COM", "I"]
ignore = ["E731"]
isort.lines-after-imports = 2
